site_name: Synthesizer V Studio Unofficial User Manual
site_url: https://manual.synthv.info/
site_description: The unofficial user manual for SynthV Studio
nav:
  - Home: index.md
  - Quickstart Guide:
    - Workspace:
      - Layout: workspace/layout.md
      - Arrangement: workspace/arrangement.md
      - Piano Roll: workspace/piano-roll.md
      - Side Panels: workspace/side-panels.md
    - Singer Selection: quickstart/singer-selection.md
    - Setting Up the Score: quickstart/setting-up-the-score.md
    - Adding Notes: quickstart/creating-notes.md
    - Editing Notes: quickstart/editing-notes.md
    - Entering Lyrics: quickstart/entering-lyrics.md
    - Playback: quickstart/playback.md
    - Managing Tracks: quickstart/managing-tracks.md
    - Saving the Audio: quickstart/saving-the-audio.md
  - Intermediate and Advanced Usage:
    - AI Functions:
  #     - Auto Pitch Tuning: ai-functions/auto-pitch-tuning.md
      - Instant Mode: ai-functions/instant-mode.md
      - AI Retakes: ai-functions/ai-retakes.md
  #   - Note Properties:
  #     - Pitch Transition and Vibrato: note-properties/pitch-transition-and-vibrato.md
  #     - Editing Phonemes: note-properties/editing-phonemes.md
  #     - Phoneme Timing: note-properties/phoneme-timing.md
  #     - Expression Groups: note-properties/expression-groups.md
  #   - User Dictionaries: advanced/user-dictionaries.md
  #   - Groups: advanced/groups.md
  #   - Editing Parameters:
  #     - Parameters Panel: parameters/parameters-panel.md
  #     - Parameter Types: parameters/parameter-types.md
  #     - Editing Parameters: parameters/editing-parameters.md
  #   - Scripts: advanced/scripts.md
  #   - License and Updates:
  #     - License Management: advanced/license-management.md
  #     - Software Updates: advanced/software-updates.md
  - Other Topics:
    - Help & Support: support.md
    - About: about.md
theme:
  name: material
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.path
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/theme.css
plugins:
  - search:
      lang: en
  - social:
      cards_color:
        fill: "#2A2A2A"
        text: "#7DB235"
  - glightbox
  - git-revision-date
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys:
      key_map:
        mouse-wheel: "Mouse wheel"